content: |-
  {{ .Header }}

  ## About

  Module for creating a Key Vault for notifier secrets.
  
  {{ .Requirements }}

  {{ .Providers }}

  {{ .Modules }}

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Footer }}