content: |-
  {{ .Header }}

  ## About

  Module for optional BigQuery remote function to call file notifier.
  
  {{ .Requirements }}

  {{ .Providers }}

  {{ .Modules }}

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Footer }}