project      = "hanki-2694-ade-proservicesdemo"
app          = "reference-notifier"
env          = "dev"
region       = "europe-west1"
source_data_bucket = "adedemo-sourcedata-dev"
state_bucket = "reference-notifier-tfstate-dev"
cidr_range   = "10.9.0.0/28"