content: |-
  {{ .Header }}

  ## About

  Module for creating a virtual network, network security group, NAT gateway and public ip for the notifier Function App.
  
  {{ .Requirements }}

  {{ .Providers }}

  {{ .Modules }}

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Footer }}