content: |-
  {{ .Header }}

  ## About

  This module creates Cloud Scheduler schedules, if those are given in the configuration files.

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Modules }}

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Footer }}