project      = "hanki-2832-adeproservdemo-prod"
app          = "reference-notifier"
env          = "prod"
region       = "europe-west1"
source_data_bucket = "adedemo-sourcedata-prod"
state_bucket = "reference-notifier-tfstate-prod"
cidr_range   = "10.11.0.0/28"
vpc_connector_name = "vpcac-adenf-prod"