parameters:
  max_files_per_manifest: 1000
schedules:
  - schedule_id: 1
    name: daily_0200
    cron: "0 2 * * *"
  - schedule_id: 2
    name: daily_0400
    cron: "0 4 * * *"
source_systems:
  - ade_source_system: ny_tlc
    single_file_manifest: true
    fullscanned: true
    schedule_id: 1
    entities:
      - ade_source_entity: yellow_tripdata_bq
        file_location: ny_tlc/yellow_tripdata
        format: PARQUET
      - ade_source_entity: green_tripdata_bq
        file_location: ny_tlc/green_tripdata
        format: PARQUET
      - ade_source_entity: taxi_zone_bq
        file_location: ny_tlc/taxi_zone
        format: CSV
        delim: COMMA
        skiph: 1
      - file_location: ny_tlc/taxi_zone_geography
        ade_source_entity: taxi_zone_geography_bq
        format: JSON
  - ade_source_system: digitraffic
    single_file_manifest: false
    fullscanned: false
    dag_trigger: DV_DIGITRAFFIC_BQ
    schedule: ""
    entities:
      - ade_source_entity: metadata_vessels_bq
        file_location: digitraffic/metadata_vessels/
        schedule_id: 1
        format: JSON
      - ade_source_entity: locations_latest_bq
        file_location: digitraffic/locations_latest/
        format: CSV
        delim: SEMICOLON
        schedule_id: 2
        skiph: 1
        compression: GZIP