content: |-
  {{ .Header }}

  ## About

  Module for creating a storage account with queues for triggering the functions and blob containers for function files.
  
  {{ .Requirements }}

  {{ .Providers }}

  {{ .Modules }}

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Footer }}