content: |-
  {{ .Header }}

  ## About

  This module generates File Event Processor Cloud Function.

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Modules }}

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Footer }}