content: |-
  {{ .Header }}

  ## About

  Module for creating an event subscription for Microsoft.Storage.BlobCreated events from an Event Grid system topic with a storage queue endpoint. Also assigns Storage Queue Data Message Sender role for the system topic to the storage account.
  
  {{ .Requirements }}

  {{ .Providers }}

  {{ .Modules }}

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Footer }}